platform:
  - x64

configuration:
  - Debug

image:
  - Visual Studio 2019

# Dont build with Visual Studio project
build: off

before_build:
  - ps: |
      mkdir build
      cd build
      cmake ../Engine

build_script:
  - cmake --build .

test_script:
  - ctest -C Debug