platform:
  - x86
  - x64

configuration:
  - Debug

image:
  - Visual Studio 2019

before_build:
  - ps: |
      mkdir build
      cd build

      $env:generator="Visual Studio 16 2019"
      if ($env:PLATFORM -eq "x64") {
          $env:generator="$env:generator Win64"
      }

      cmake .. -G "$env:generator"

build_script:
  - cmake --build .
