platform:
  - x64

configuration:
  - Debug

image:
  - Visual Studio 2019

# Dont build with Visual Studio project
build: off

before_build:
  - ps: |
      ls
      mkdir build
      ls
      cd build
      cmake ../Engine -G "Visual Studio 16 2019"

build_script:
  - cmake --build .

test_script:
  - ctest -C Debug