kind: pipline
type: docker
name: linux

steps:
- name: build
  image: ubuntu
  commands:
  - /bin/bash -c "
    apt-get update && apt-get install -y ninja-build &&
    git clone https://github.com/zacharyselk/Trundle &&
    mkdir build && cd build &&
    cmake .. -G Ninja &&
    ninja"