extraction:
  cpp:
    after_prepare: "(mkdir -p ${LGTM_SRC}/cmake.3.18; curl -o cmake3.18.tar.gz -L https://github.com/Kitware/CMake/releases/download/v3.18.1/cmake-3.18.1-Linux-x86_64.tar.gz; tar xpozf cmake3.18.tar.gz --strip-components 1 -C ${LGTM_SRC}/cmake.3.18; mkdir -p ${LGTM_SRC}/build)"
    configure:
      command: "(cd ${LGTM_SRC}/build; ${LGTM_SRC}/cmake.3.18/bin/cmake ../Engine -DTEST_HEADLESS=On)"
    index:
      build_command: "(cd ${LGTM_SRC}/build; ${LGTM_SRC}/cmake.3.18/bin/cmake --build .)"