language: cpp
os: linux
compiler: gcc

cache:
- directories:
  - $HOME/.cache

addons:
  apt:
    packages: lcov

install:
  # (fake) install dependencies (usually involves wget, configure, make, ...)
  # install into cache folder (build binaries+headers only, no sources and do NOT build there)
  - mkdir -p $HOME/.cache
  - touch $HOME/.cache/mydependency.so


before_script:
  - mkdir build
  - cd build
  - cmake ..

script:
  - cmake --build .

after_success:
  - lcov --directory . --capture --output-file coverage.info
  #- lcov --remove coverage.info '/usr/*' "${HOME}"'/.cache/*' --output-file coverage.info
  - lcov --list coverage.info
  - bash <(curl -s https://codecov.io/bash) -f coverage.info || echo "Codecov did not collect coverage reports"