language: cpp
os: linux
compiler: gcc

cache:
- directories:
  - $HOME/.cache

addons:
  apt:
    packages: lcov

install:
  # (fake) install dependencies (usually involves wget, configure, make, ...)
  # install into cache folder (build binaries+headers only, no sources and do NOT build there)
  - mkdir -p $HOME/.cache

  # Download CMake 3.18 binaries
  - mkdir -p $HOME/.cache/cmake3.18
  - wget -qO- https://github.com/Kitware/CMake/releases/download/v3.18.1/cmake-3.18.1-Linux-x86_64.tar.gz | tar xpoz -C $HOME/.cache/cmake3.18 --strip-components 1
  - export PATH=$HOME/.cache/cmake3.18/bin:$PATH

  - apt-get install -y libxrandr-dev


before_script:
  - mkdir build
  - cd build
  - cmake ..

script:
  - cmake --build .

after_success:
  - lcov --directory . --capture --output-file coverage.info
  #- lcov --remove coverage.info '/usr/*' "${HOME}"'/.cache/*' --output-file coverage.info
  - lcov --list coverage.info
  - bash <(curl -s https://codecov.io/bash) -f coverage.info || echo "Codecov did not collect coverage reports"